services:
  intranet_ai_backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3034:3034"
    volumes:
      - ./src:/app/src # Scripts
      - ../data:/app/data
